version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    container_name: postgres_test
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: test
    ports:
      - "5434:5432"
    volumes:
      - dbdata_test:/var/lib/postgresql/data
  go:
    container_name: go
    build:
      context: .
    depends_on:
      postgres:
       condition: service_healthy
    ports:
      - "3000:3000"

volumes:
  dbdata:
  dbdata_test: